#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}
        # sh +x /sbin/sig.sh &
	# set leds to normal state
	# sh +x /sbin/pppcheck.sh &
        . /etc/diag.sh
	set_state done
}
